# Generated by Django 5.2.4 on 2025-08-18 12:56

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-year', '-month', 'category__name']},
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_period_and_category',
        ),
        migrations.AddField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'period', 'year', 'month')},
        ),
    ]
